#!/usr/bin/perl
use strict;
use Carp;
# pnfo
# NFO files are ASCII-art with the cp437 codepage
# Lucida ConsoleP has support for all the cp437 chars

my $term = "urxvt -fn xft:'Lucida ConsoleP:pixelsize=10:antialias=0' -fg '#ffffff' -uc +sb";
my $viewer = "vimpager-nfo";

my @nfos;
my $dir = shift;

if(!$dir) {
  @nfos = grep{/\.nfo$/} glob("./*");
}

if(-f $dir and $dir =~ /\.nfo$/) {
  system("$term -e $viewer \"$dir\"") == 0 or croak();
  exit 0;
}

if(-d $dir) {
  @nfos = grep{/\.nfo$/} glob("$dir/*");
  if(!@nfos) {
    print "No NFO's here!\n";
    exit 1;
  }
}

for my $nfo(@nfos) {
  system("$term -e $viewer \"$nfo\"") == 0 or croak();
}


