#!/usr/bin/perl
use strict;
use Carp;
# pnfo
# NFO files are ASCII-art with the cp437 codepage
# Lucida ConsoleP has support for all the cp437 chars

my $term = "urxvt -fn xft:'Lucida ConsoleP:pixelsize=10:antialias=0' -fg '#ffffff' -uc +sb";
my $viewer = "vimpager-nfo";

my(@nfos) = (undef);

view(find("./")) unless(@ARGV);

sub find {
  my $dir = shift;
  return(1) unless(-d $dir);

  for(glob("$dir/*")) {
    if(-d $_) {
      find($_);
    }
    elsif(-f $_ and $_ =~ /\.nfo$/) {
      push(@nfos, $_);
    }
  }
  return(@nfos);
}

sub view {
  my @files = @_;
  for my $file(@files) {
    system("$term -e $viewer \"$file\"") == 0 or croak();
  }
}


