#!/bin/sh
# modded vimpager for nfo files
# colorscheme is at http://github.com/trapd00r/neverland-vim-theme


file="$@"
if [ -z "$file" ]; then file="-"; fi

less_vim() {
    /usr/bin/vim -pR \
    -c 'let no_plugin_maps = 1' \
    -c 'set scrolloff=999' \
    -c 'runtime! macros/less.vim' \
    -c 'set foldlevel=999' \
    -c 'set nonumber' \
    -c 'set laststatus=2' \
    -c 'set colorcolumn=0 ft=b cursorline tw=80' \
    "$@"
}

less_vim "$file"
